apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: prod-
replicas:
- name: gateway
  count: 3
- name: auth-service
  count: 3
- name: files-service
  count: 3
