apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: bitnami/postgresql:16
            command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y awscli gzip
              /scripts/backup.sh
            envFrom:
            - configMapRef:
                name: cloudvault-config
            - secretRef:
                name: cloudvault-secret
            volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
          volumes:
          - name: scripts-volume
            configMap:
              name: scripts-configmap
              defaultMode: 0755
          restartPolicy: OnFailure
