apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thumbnail-worker
  template:
    metadata:
      labels:
        app: thumbnail-worker
    spec:
      containers:
      - name: thumbnail-worker
        image: cloudvault-thumbnail-worker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: cloudvault-config
        - secretRef:
            name: cloudvault-secret
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
